version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./api:/app  # Mount ./api to /app inside the container
    environment:
      - PYTHONPATH=/app  
    command: ["conda", "run", "--no-capture-output", "-n", "ts", "python", "/app/app.py"]

  test:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./api:/app  # Mount ./api to /app inside the container
    environment:
      - PYTHONPATH=/app  
      - COMPLEX_SENTENCE=This is a complex sentence to be simplified.
      - CONTINUE=n
    command: ["conda", "run", "--no-capture-output", "-n", "ts", "python", "/app/inference/simplify.py"]